In [1]:
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC

In [2]:
df_math = pd.read_excel("student-math.xlsx")

In [3]:
df_math

Gender  age famsize  traveltime  studytime activities  freetime  goout  \
0        F   18     GT3           2          2         no         3      4   
1        F   17     GT3           1          2         no         3      3   
2        F   15     LE3           1          2         no         3      2   
3        F   15     GT3           1          3        yes         2      2   
4        F   16     GT3           1          2         no         3      2   
..     ...  ...     ...         ...        ...        ...       ...    ...   
390      M   20     LE3           1          2         no         5      4   
391      M   17     LE3           2          1         no         4      5   
392      M   21     GT3           1          1         no         5      3   
393      M   18     LE3           3          1         no         4      1   
394      M   19     LE3           1          1         no         2      3   

     absences  G1  G2  G3  
0           6   5   6   6  
1           4   5   5   6  
2          10   7   8  10  
3           2  15  14  15  
4           4   6  10  10  
..        ...  ..  ..  ..  
390        11   9   9   9  
391         3  14  16  16  
392         3  10   8   7  
393         0  11  12  10  
394         5   8   9   9  

[395 rows x 12 columns]

In [4]:


codes_gender, uniques_gender = pd.factorize(df_math["Gender"])



In [5]:
codes_gender

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,

In [6]:
uniques_gender

Index(['F', 'M'], dtype='object')

In [7]:
df_math["gender factorized"] = np.array(codes_gender)

In [8]:
codes_fam, uniques_fam = pd.factorize(df_math["famsize"])

In [9]:
codes_fam

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1,

In [10]:
uniques_fam

Index(['GT3', 'LE3'], dtype='object')

In [11]:
df_math["fam size factorized"] = np.array(codes_fam)

In [12]:
codes_activities, uniques_activities = pd.factorize(df_math["activities"])

In [13]:
codes_activities

array([0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,

In [14]:
uniques_activities

Index(['no', 'yes'], dtype='object')

In [15]:
df_math["activities factorized"] = np.array(codes_activities)

In [16]:
df_math

Gender  age famsize  traveltime  studytime activities  freetime  goout  \
0        F   18     GT3           2          2         no         3      4   
1        F   17     GT3           1          2         no         3      3   
2        F   15     LE3           1          2         no         3      2   
3        F   15     GT3           1          3        yes         2      2   
4        F   16     GT3           1          2         no         3      2   
..     ...  ...     ...         ...        ...        ...       ...    ...   
390      M   20     LE3           1          2         no         5      4   
391      M   17     LE3           2          1         no         4      5   
392      M   21     GT3           1          1         no         5      3   
393      M   18     LE3           3          1         no         4      1   
394      M   19     LE3           1          1         no         2      3   

     absences  G1  G2  G3  gender factorized  fam size factorized  \
0           6   5   6   6                  0                    0   
1           4   5   5   6                  0                    0   
2          10   7   8  10                  0                    1   
3           2  15  14  15                  0                    0   
4           4   6  10  10                  0                    0   
..        ...  ..  ..  ..                ...                  ...   
390        11   9   9   9                  1                    1   
391         3  14  16  16                  1                    1   
392         3  10   8   7                  1                    0   
393         0  11  12  10                  1                    1   
394         5   8   9   9                  1                    1   

     activities factorized  
0                        0  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
390                      0  
391                      0  
392                      0  
393                      0  
394                      0  

[395 rows x 15 columns]

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

#Linear regression
X = pd.DataFrame()

X["gender"] = df_math['gender factorized']
X["age"] = df_math['age']
X["fam_size_Fact"] = df_math['fam size factorized']
X['travel'] = df_math['traveltime']
X['study'] = df_math["studytime"]
X['activities'] = df_math['activities factorized']
X['free'] = df_math['freetime']
X['out'] = df_math['goout']
X['absences'] = df_math['absences']                     

y = pd.DataFrame()
y['mid1'] = df_math['G2']

X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = LinearRegression()

model.fit(X_train, y_train)

y_predict = model.predict(x_test)
print(r2_score(y_test, y_predict))
print(mean_absolute_error(y_test, y_predict))
print(mean_squared_error(y_test, y_predict))



0.03603135824621062
3.207063910041248
16.149139139549064


In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

#Linear regression
X = pd.DataFrame()

X["gender"] = df_math['gender factorized']
X["age"] = df_math['age']
X["fam_size_Fact"] = df_math['fam size factorized']
X['travel'] = df_math['traveltime']
X['study'] = df_math["studytime"]
X['activities'] = df_math['activities factorized']
X['free'] = df_math['freetime']
X['out'] = df_math['goout']
X['absences'] = df_math['absences']                     

y = pd.DataFrame()
y['mid1'] = df_math['G2']

X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = MLPRegressor(random_state=0)

model.fit(X_train, y_train)

y_predict = model.predict(x_test)
print(r2_score(y_test, y_predict))
print(mean_absolute_error(y_test, y_predict))
print(mean_squared_error(y_test, y_predict))



-0.047475807752509924
3.427554539507174
17.54811498217528


/Users/andreisandor/anaconda3/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:1617: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/andreisandor/anaconda3/lib/python3.10/site-packages/sklearn/neural_network/_multilayer_perceptron.py:684: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

#Linear regression
X = pd.DataFrame()

X["gender"] = df_math['gender factorized']
X["age"] = df_math['age']
X["fam_size_Fact"] = df_math['fam size factorized']
X['travel'] = df_math['traveltime']
X['study'] = df_math["studytime"]
X['activities'] = df_math['activities factorized']
X['free'] = df_math['freetime']
X['out'] = df_math['goout']
X['absences'] = df_math['absences']                     

y = pd.DataFrame()
y['mid1'] = df_math['G2']

X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = DecisionTreeRegressor(random_state=0)

model.fit(X_train, y_train)

y_predict = model.predict(x_test)
print(r2_score(y_test, y_predict))
print(mean_absolute_error(y_test, y_predict))
print(mean_squared_error(y_test, y_predict))



-0.3237944028922852
3.7974683544303796
22.17721518987342


In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

#Linear regression
X = pd.DataFrame()

X["gender"] = df_math['gender factorized']
X["age"] = df_math['age']
X["fam_size_Fact"] = df_math['fam size factorized']
X['travel'] = df_math['traveltime']
X['study'] = df_math["studytime"]
X['activities'] = df_math['activities factorized']
X['free'] = df_math['freetime']
X['out'] = df_math['goout']
X['absences'] = df_math['absences']                     

y = pd.DataFrame()
y['mid1'] = df_math['G2']

X_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

model = RandomForestRegressor(random_state=0)

model.fit(X_train, y_train)

y_predict = model.predict(x_test)
print(r2_score(y_test, y_predict))
print(mean_absolute_error(y_test, y_predict))
print(mean_squared_error(y_test, y_predict))



0.10177478968762554
3.159126582278481
15.04775494936709


/var/folders/zp/j6n5zjwx4g184f0x4g1j4llc0000gn/T/ipykernel_90167/224380791.py:25: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train, y_train)
